services:
  caddy:
    image: caddy:2.10.2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./src/webgl-shader:/srv/webgl-shaders:ro
    restart: unless-stopped
